media:
  input: src/media
  output: src/media
content:
  - name: news
    label: News
    type: collection
    path: src/content/news
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: description
        label: Description
        type: string
        required: true
      - name: date
        label: Date
        type: date
        required: true
      - name: listserv
        label: Mailing List
        type: select
        options:
          values:
            - name: igwc-ue-l
              label: Member Email List
            - name: igwc-ue-news-l
              label: Newsletter
        description: Select which footer (with social media and unsubscribe links) will be appended to the newsletter when sent as an email
      - name: body
        type: rich-text
